build_from:
  amd64: ghcr.io/home-assistant/amd64-base:latest
  aarch64: ghcr.io/home-assistant/aarch64-base:latest
args:
  STASH_VERSION: v0.27.2
labels:
  org.opencontainers.image.title: "Stash"
  org.opencontainers.image.description: "An organizer for your media with a web-based UI"
  org.opencontainers.image.source: "https://github.com/zer0sis/hass-addons"
  org.opencontainers.image.licenses: "AGPL-3.0"
