build_from:
  amd64: stashapp/stash:latest
  aarch64: stashapp/stash:latest
labels:
  org.opencontainers.image.title: "Stash"
  org.opencontainers.image.description: "An organizer for your media with a web-based UI"
  org.opencontainers.image.source: "https://github.com/zer0sis/hass-addons"
  org.opencontainers.image.licenses: "AGPL-3.0"
